import type {Metadata} from 'next';

// These styles apply to every route in the application
import './globals.css';
import Footer from '../components/layouts/Footer';
import NavBar from '../components/layouts/NavBar';

export const metadata: Metadata = {
  title: "Lorenzo's Website",
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
