import type {Metadata} from 'next';

// These styles apply to every route in the application
import './globals.css';
import Header from '../components/sections/Header';
import Footer from '../components/sections/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      {/* <Header/> */}
      <body>{children}</body>
      <Footer />
    </html>
  );
}
