/**
 * Generates src/generated/blog-provenance.ts from each essay's git history:
 * when it was first written, when it was last revised, and how many times.
 * Run via `npm run generate-blog-provenance` (and in predeploy). Honesty as a
 * feature — the article footer shows that an essay evolved.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const BLOG_DIR = path.join(process.cwd(), 'src', 'app', 'blog');
const OUT = path.join(process.cwd(), 'src', 'generated', 'blog-provenance.ts');

interface Provenance {
  firstWritten: string; // ISO date (YYYY-MM-DD)
  lastRevised: string;
  revisions: number; // number of commits that touched the content
}

function gitDates(relPath: string): string[] {
  try {
    // execFile (no shell) — args are passed directly, so the path can't be
    // interpreted as shell syntax.
    const out = execFileSync(
      'git',
      ['log', '--follow', '--format=%ad', '--date=short', '--', relPath],
      { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'] }
    );
    return out.split('\n').map((l) => l.trim()).filter(Boolean);
  } catch (err) {
    // git missing, or a shallow clone (CI default: actions/checkout uses
    // fetch-depth 1) where `--follow` history isn't present. Surface it under
    // CI so we don't deploy empty colophons unnoticed.
    if (process.env.CI) {
      console.warn(
        `⚠️  git history unavailable for ${relPath}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
    return [];
  }
}

function main() {
  const slugs = fs
    .readdirSync(BLOG_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((slug) => fs.existsSync(path.join(BLOG_DIR, slug, 'content.mdx')))
    .sort();

  const provenance: Record<string, Provenance> = {};
  for (const slug of slugs) {
    const rel = path.join('src', 'app', 'blog', slug, 'content.mdx');
    const dates = gitDates(rel);
    if (dates.length === 0) continue; // uncommitted / untracked — skip
    provenance[slug] = {
      firstWritten: dates[dates.length - 1], // oldest commit
      lastRevised: dates[0], // newest commit
      revisions: dates.length,
    };
  }

  // A non-empty set of essays that produced zero provenance almost always means
  // git history is missing (shallow clone), not that every post is uncommitted.
  if (slugs.length > 0 && Object.keys(provenance).length === 0) {
    console.warn(
      `⚠️  No provenance generated for ${slugs.length} essays — git history is ` +
        `unavailable (shallow clone?); article colophons will be empty. ` +
        `Ensure full history (e.g. actions/checkout with fetch-depth: 0).`,
    );
  }

  const body =
    `// This file is auto-generated by scripts/generate-blog-provenance.ts\n` +
    `// Do not edit manually. Regenerate with: npm run generate-blog-provenance\n\n` +
    `export interface BlogProvenance {\n` +
    `  firstWritten: string;\n  lastRevised: string;\n  revisions: number;\n}\n\n` +
    `export const BLOG_PROVENANCE: Record<string, BlogProvenance> = ${JSON.stringify(
      provenance,
      null,
      2
    )};\n`;

  fs.writeFileSync(OUT, body);
  console.log(`Wrote provenance for ${Object.keys(provenance).length} essays → ${path.relative(process.cwd(), OUT)}`);
}

main();
