import fs from "fs/promises";
import path from "path";

const REPO_ROOT = process.cwd();
const AUDIO_DIR = path.join(REPO_ROOT, "public", "audio");
const OUT_FILE = path.join(REPO_ROOT, "src", "generated", "audio-manifest.ts");

function fileNameToSlug(fileName: string): string {
  return fileName.replace(/\.mp3$/i, "");
}

async function main(): Promise<void> {
  const dirEntries = await fs.readdir(AUDIO_DIR, { withFileTypes: true });
  const mp3Files = dirEntries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".mp3"))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));

  const pairs = await Promise.all(
    mp3Files.map(async (fileName) => {
      const slug = fileNameToSlug(fileName);
      const stat = await fs.stat(path.join(AUDIO_DIR, fileName));
      return [slug, stat.size] as const;
    })
  );

  pairs.sort((a, b) => a[0].localeCompare(b[0]));

  const lines: string[] = [];
  lines.push("// This file is auto-generated by scripts/generate-audio-manifest.ts");
  lines.push("// Do not edit manually.");
  lines.push("");
  lines.push("export const AUDIO_BYTES_BY_SLUG: Record<string, number> = {");

  for (const [slug, size] of pairs) {
    lines.push(`  ${JSON.stringify(slug)}: ${size},`);
  }

  lines.push("};");
  lines.push("");

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, lines.join("\n"), "utf8");

  console.log(`Wrote ${OUT_FILE} with ${pairs.length} entries.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
