"use client"

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, ChevronDown, Loader2 } from 'lucide-react'

interface AISummaryProps {
  content: string
}

export function AISummary({ content }: AISummaryProps) {
  const [summary, setSummary] = useState<string>('')
  const [takeaways, setTakeaways] = useState<string[]>([])
  const [isExpanded, setIsExpanded] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [hasGenerated, setHasGenerated] = useState(false)

  const generateSummary = async () => {
    if (hasGenerated) {
      setIsExpanded(!isExpanded)
      return
    }

    setIsLoading(true)
    setIsExpanded(true)

    try {
      // Generate both summary and takeaways in parallel
      const [summaryRes, takeawaysRes] = await Promise.all([
        fetch('/api/summarize', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ content, type: 'summary' }),
        }),
        fetch('/api/summarize', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ content, type: 'takeaways' }),
        }),
      ])

      const summaryData = await summaryRes.json()
      const takeawaysData = await takeawaysRes.json()

      setSummary(summaryData.summary || '')
      setTakeaways(takeawaysData.takeaways || [])
      setHasGenerated(true)
    } catch (error) {
      console.error('Failed to generate summary:', error)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="my-8 rounded-lg border-2 border-purple-200 dark:border-purple-800 overflow-hidden">
      <button
        onClick={generateSummary}
        className="w-full p-4 flex items-center justify-between bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/20 dark:to-pink-950/20 hover:from-purple-100 hover:to-pink-100 dark:hover:from-purple-950/30 dark:hover:to-pink-950/30 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-900/40">
            <Sparkles className="h-5 w-5 text-purple-600 dark:text-purple-400" />
          </div>
          <div className="text-left">
            <h3 className="font-semibold text-foreground">
              {hasGenerated ? 'AI Summary' : 'Generate AI Summary'}
            </h3>
            <p className="text-sm text-muted-foreground">
              {hasGenerated ? 'Click to expand/collapse' : 'Get a quick TL;DR and key takeaways'}
            </p>
          </div>
        </div>
        {isLoading ? (
          <Loader2 className="h-5 w-5 animate-spin text-purple-600" />
        ) : (
          <ChevronDown
            className={`h-5 w-5 text-purple-600 transition-transform ${
              isExpanded ? 'rotate-180' : ''
            }`}
          />
        )}
      </button>

      <AnimatePresence>
        {isExpanded && hasGenerated && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="border-t border-purple-200 dark:border-purple-800"
          >
            <div className="p-6 space-y-6 bg-white dark:bg-gray-950">
              {summary && (
                <div>
                  <h4 className="text-sm font-semibold mb-2 text-purple-600 dark:text-purple-400">
                    TL;DR
                  </h4>
                  <p className="text-muted-foreground leading-relaxed">{summary}</p>
                </div>
              )}

              {takeaways.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold mb-3 text-purple-600 dark:text-purple-400">
                    Key Takeaways
                  </h4>
                  <ul className="space-y-2">
                    {takeaways.map((takeaway, index) => (
                      <motion.li
                        key={index}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="flex items-start gap-2"
                      >
                        <span className="text-purple-600 dark:text-purple-400 mt-1">•</span>
                        <span className="text-sm text-muted-foreground">{takeaway}</span>
                      </motion.li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="text-xs text-muted-foreground pt-4 border-t border-gray-200 dark:border-gray-800">
                Generated by AI • May not be 100% accurate
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
